defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "Dino-CyclOPS-vit_c-KNN"
weights_init: "/path/to/weights" # "random-weights" or "imagenet-weights"
method: "dino"

backbone:
  name: "vit_channels"
  kwargs:
    embed_dim: 192
    patch_size: 16
    return_all_tokens: False
    max_number_channels: 10    # maximum number of channels that was used during pretraining

knn_eval:
  enabled: False

knn_eval_offline:
  enabled: True
  k: [1,2,5,10,20,50,100,200]
  temperature: [0.01, 0.02, 0.05, 0.07, 0.1, 0.2, 0.5, 1]
  feature_type: ["backbone"]
  distance_function: ["cosine", "euclidean"]

method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 4096
  warmup_teacher_temperature_epochs: 50

momentum:
  base_tau: 0.9995
  final_tau: 1.0

data:
  dataset: cyclops
  train_path: "/path/to/train/data"
  val_path: "/path/to/val/data"
  format: "image_folder"
  num_workers: 4
  img_channels: 2
  max_img_channels: 2

optimizer:
  name: "lars"
  batch_size: 8
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True

scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1

auto_resume:
  enabled: True

channels_strategy: "multi_channels"
mixed_channels: False

# overwrite PL stuff
max_epochs: 400
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
#precision: 16-mixed
